<?php

return [
    [
        'id' => 'alexander-palm',
        'common_name' => 'Alexander Palm',
        'scientific_name' => 'Archontophoenix alexandrae',
        'image' => 'images/palms/alexander-palm-2.png',
    ],
    [
        'id' => 'ampasindavae-palm',
        'common_name' => 'Ampasindavae Palm',
        'scientific_name' => '',
        'image' => 'images/palms/ampasindavae-palm.png',
    ],
    [
        'id' => 'australian-fan-palm',
        'common_name' => 'Australian Fan Palm',
        'scientific_name' => 'Licuala ramsayi',
        'image' => 'images/palms/australian-fan-palm.png',
    ],
    [
        'id' => 'bangalow-palm',
        'common_name' => 'Bangalow Palm',
        'scientific_name' => 'Archontophoenix cunninghamiana',
        'image' => 'images/palms/bangalow-palm-2.png',
    ],
    [
        'id' => 'bismarck-palm',
        'common_name' => 'Bismarck Palm',
        'scientific_name' => 'Bismarckia nobilis',
        'image' => 'images/palms/bismarck-palm.png',
    ],
    [
        'id' => 'blue-cane-palm',
        'common_name' => 'Blue Cane Palm',
        'scientific_name' => 'Dypsis cabadae',
        'image' => 'images/palms/blue-cane-palm.png',
    ],
    [
        'id' => 'bottle-palm',
        'common_name' => 'Bottle Palm',
        'scientific_name' => 'Hyophorbe lagenicaulis',
        'image' => 'images/palms/bottle-palm.png',
    ],
    [
        'id' => 'canary-island-date-palm',
        'common_name' => 'Canary Island Date Palm',
        'scientific_name' => 'Phoenix canariensis',
        'image' => 'images/palms/canary-island-date-palm-2.png',
    ],
    [
        'id' => 'carnarvon-gorge-palm',
        'common_name' => 'Carnarvon Gorge Palm',
        'scientific_name' => 'Livistona nitida',
        'image' => 'images/palms/carnarvon-gorge-palm.png',
    ],
    [
        'id' => 'chinese-fan-palm',
        'common_name' => 'Chinese Fan Palm',
        'scientific_name' => 'Livistona chinensis',
        'image' => 'images/palms/chinese-fan-palm.png',
    ],
    [
        'id' => 'coconut-palm',
        'common_name' => 'Coconut Palm',
        'scientific_name' => 'Cocos nucifera',
        'image' => 'images/palms/coconut-palm-2.png',
    ],
    [
        'id' => 'dwarf-areca-catechu-palm',
        'common_name' => 'Dwarf Areca Catechu Palm',
        'scientific_name' => 'Areca catechu',
        'image' => 'images/palms/dwarf-areca-catechu-palm.png',
    ],
    [
        'id' => 'dwarf-date-palm',
        'common_name' => 'Dwarf Date Palm',
        'scientific_name' => 'Phoenix roebelenii',
        'image' => 'images/palms/dwarf-date-palm.png',
    ],
    [
        'id' => 'fine-leaf-palm',
        'common_name' => 'Fine Leaf Palm',
        'scientific_name' => '',
        'image' => 'images/palms/fine-leaf-palm.png',
    ],
    [
        'id' => 'foxtail-palm',
        'common_name' => 'Foxtail Palm',
        'scientific_name' => 'Wodyetia bifurcata',
        'image' => 'images/palms/foxtail-palm.png',
    ],
    [
        'id' => 'golden-cane-palm',
        'common_name' => 'Golden Cane Palm',
        'scientific_name' => 'Dypsis lutescens',
        'image' => 'images/palms/golden-cane-palm.png',
    ],
    [
        'id' => 'hurricane-palm',
        'common_name' => 'Hurricane Palm',
        'scientific_name' => 'Dictyosperma album',
        'image' => 'images/palms/hurricane-palm.png',
    ],
    [
        'id' => 'kentia-palm',
        'common_name' => 'Kentia Palm',
        'scientific_name' => 'Howea forsteriana',
        'image' => 'images/palms/kentia-palm-2.png',
    ],
    [
        'id' => 'king-palm',
        'common_name' => 'King Palm',
        'scientific_name' => 'Archontophoenix cunninghamiana',
        'image' => 'images/palms/king-palm.png',
    ],
    [
        'id' => 'madagascar-cane-palm',
        'common_name' => 'Madagascar Cane Palm',
        'scientific_name' => '',
        'image' => 'images/palms/madagascar-cane-palm.png',
    ],
    [
        'id' => 'malay-dwarf-coconut-palm',
        'common_name' => 'Malay Dwarf Coconut Palm',
        'scientific_name' => 'Cocos nucifera',
        'image' => 'images/palms/malay-dwarf-coconut-palm.png',
    ],
    [
        'id' => 'manambe-palm',
        'common_name' => 'Manambe Palm',
        'scientific_name' => '',
        'image' => 'images/palms/manambe-palm.png',
    ],
    [
        'id' => 'queensland-black-palm',
        'common_name' => 'Queensland Black Palm',
        'scientific_name' => 'Normanbya normanbyi',
        'image' => 'images/palms/queensland-black-palm.png',
    ],
    [
        'id' => 'redneck-palm',
        'common_name' => 'Redneck Palm',
        'scientific_name' => 'Dypsis leptocheilos',
        'image' => 'images/palms/redneck-palm.png',
    ],
    [
        'id' => 'rigid-fan-palm',
        'common_name' => 'Rigid Fan Palm',
        'scientific_name' => '',
        'image' => 'images/palms/rigid-fan-palm.png',
    ],
    [
        'id' => 'sago-palm',
        'common_name' => 'Sago Palm',
        'scientific_name' => 'Cycas revoluta',
        'image' => 'images/palms/sago-palm.png',
    ],
    [
        'id' => 'senegal-date-palm',
        'common_name' => 'Senegal Date Palm',
        'scientific_name' => 'Phoenix reclinata',
        'image' => 'images/palms/senegal-date-palm.png',
    ],
    [
        'id' => 'spindle-palm',
        'common_name' => 'Spindle Palm',
        'scientific_name' => 'Hyophorbe verschaffeltii',
        'image' => 'images/palms/spindle-palm.png',
    ],
    [
        'id' => 'teddy-bear-palm',
        'common_name' => 'Teddy Bear Palm',
        'scientific_name' => 'Dypsis leptocheilos',
        'image' => 'images/palms/teddy-bear-palm.png',
    ],
    [
        'id' => 'triangle-palm',
        'common_name' => 'Triangle Palm',
        'scientific_name' => 'Dypsis decaryi',
        'image' => 'images/palms/triangle-palm.png',
    ],
    [
        'id' => 'triple-crown-palm',
        'common_name' => 'Triple Crown Palm',
        'scientific_name' => '',
        'image' => 'images/palms/triple-crown-palm.png',
    ],
];
